// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwgwJ-7nL-QqiRddxoLwTAVDzWsuOsMe4',
    appId: '1:174638590833:web:de17218ecd1c2bf9a864d0',
    messagingSenderId: '174638590833',
    projectId: 'edugestao',
    authDomain: 'edugestao.firebaseapp.com',
    storageBucket: 'edugestao.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKXQoQpJDVPfiEqJuTYXH46xYgqjpsk6I',
    appId: '1:174638590833:android:16a462c4bbfeeda6a864d0',
    messagingSenderId: '174638590833',
    projectId: 'edugestao',
    storageBucket: 'edugestao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9USiWAqQaD_eA-09NqdYfFPtJyQJKTps',
    appId: '1:174638590833:ios:f6f4959285211237a864d0',
    messagingSenderId: '174638590833',
    projectId: 'edugestao',
    storageBucket: 'edugestao.firebasestorage.app',
    iosClientId: '174638590833-nsb8uu12pcdsa9fotn01ro0hnd8e94kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.edugestao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9USiWAqQaD_eA-09NqdYfFPtJyQJKTps',
    appId: '1:174638590833:ios:f6f4959285211237a864d0',
    messagingSenderId: '174638590833',
    projectId: 'edugestao',
    storageBucket: 'edugestao.firebasestorage.app',
    iosClientId: '174638590833-nsb8uu12pcdsa9fotn01ro0hnd8e94kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.edugestao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwgwJ-7nL-QqiRddxoLwTAVDzWsuOsMe4',
    appId: '1:174638590833:web:ab8bdd691b317643a864d0',
    messagingSenderId: '174638590833',
    projectId: 'edugestao',
    authDomain: 'edugestao.firebaseapp.com',
    storageBucket: 'edugestao.firebasestorage.app',
  );

}